server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-username/spring-config-repo
          default-label: main  # or master
          clone-on-start: true
  application:
    name: config-server